apiVersion: v1
kind: Service
metadata:
  name: clair
  namespace: clair
  labels:
    app: clair
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 6060
    targetPort: 6060
  - name: health
    port: 6061
    targetPort: 6061
  selector:
    app: clair
