apiVersion: v1
kind: Service
metadata:
  name: clair
  namespace: clair
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - name: api
    port: 6060
  - name: health
    port: 6061
  selector:
    app: clair
